import { LifeDomainItem, TaskItem, UserProfile } from "@/types";

export const INITIAL_USER_PROFILE: UserProfile = {
  id: "usr-anastasia-01",
  email: "commander@agency.dev",
  callSign: "Anastasia Nikulina",
  rankTier: 4,
  rankTitle: "Commander",
  totalXp: 4600,
  tierProgress: 92,
  nextTierXp: 5000,
};

export const INITIAL_DOMAINS: LifeDomainItem[] = [
  {
    id: "dom-health",
    userId: "usr-anastasia-01",
    name: "Health & Wellness",
    slug: "health",
    accentColor: "#10B981",
    avatarSpecies: "Vitality Wolf",
    level: 15,
    currentXp: 3400,
    isActive: true,
    skillPets: [
      {
        id: "pet-h1",
        domainId: "dom-health",
        title: "Daily 10000 steps",
        level: 15,
        currentXp: 3400,
        nextEvolutionThreshold: 4000,
        planningEngineType: "DAILY_ROUTINE",
      },
      {
        id: "pet-h2",
        domainId: "dom-health",
        title: "Doctor appointment",
        level: 1,
        currentXp: 0,
        nextEvolutionThreshold: 1000,
        planningEngineType: "SPECIFIC_DATE",
      },
    ],
  },
  {
    id: "dom-work",
    userId: "usr-anastasia-01",
    name: "Work & Projects",
    slug: "work",
    accentColor: "#3B82F6",
    avatarSpecies: "Byte Fox",
    level: 90,
    currentXp: 8200,
    isActive: true,
    skillPets: [
      {
        id: "pet-w1",
        domainId: "dom-work",
        title: "Pet Your Skills",
        level: 90,
        currentXp: 8200,
        nextEvolutionThreshold: 10000,
        planningEngineType: "MULTI_TASK",
      },
      {
        id: "pet-w2",
        domainId: "dom-work",
        title: "Code Review",
        level: 45,
        currentXp: 2100,
        nextEvolutionThreshold: 3000,
        planningEngineType: "DAILY_ROUTINE",
      },
    ],
  },
  {
    id: "dom-learning",
    userId: "usr-anastasia-01",
    name: "Learning & Growth",
    slug: "learning",
    accentColor: "#8B5CF6",
    avatarSpecies: "Hydro Dragon",
    level: 70,
    currentXp: 4500,
    isActive: true,
    skillPets: [
      {
        id: "pet-l1",
        domainId: "dom-learning",
        title: "GitHub course",
        level: 70,
        currentXp: 4500,
        nextEvolutionThreshold: 5000,
        planningEngineType: "MULTI_TASK",
      },
      {
        id: "pet-l2",
        domainId: "dom-learning",
        title: "NodeJS course",
        level: 30,
        currentXp: 1200,
        nextEvolutionThreshold: 2000,
        planningEngineType: "MULTI_TASK",
      },
    ],
  },
  {
    id: "dom-volunteering",
    userId: "usr-anastasia-01",
    name: "Volunteering",
    slug: "volunteering",
    accentColor: "#F59E0B",
    avatarSpecies: "Wisdom Owl",
    level: 38,
    currentXp: 2100,
    isActive: true,
    skillPets: [
      {
        id: "pet-v1",
        domainId: "dom-volunteering",
        title: "CYS",
        level: 38,
        currentXp: 2100,
        nextEvolutionThreshold: 3000,
        planningEngineType: "MULTI_TASK",
      },
    ],
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: "task-1",
    domainId: "dom-work",
    title: "Complete Dashboard Wireframe",
    columnId: "TODO",
    isCompleted: false,
    xpReward: 250,
    estimatedMinutes: 45,
    sortOrder: 1,
    repeatConfig: {
      frequency: "multi_task",
      startDate: "2026-09-08",
      endDate: "2026-09-15",
      engine: "MULTI_TASK",
    },
  },
  {
    id: "task-2",
    domainId: "dom-health",
    title: "Morning 5km Run",
    columnId: "DONE",
    isCompleted: true,
    doneAt: "2026-09-07T07:30:00Z",
    xpReward: 150,
    estimatedMinutes: 30,
    sortOrder: 2,
    repeatConfig: {
      frequency: "daily",
      time: "07:00",
      engine: "DAILY_ROUTINE",
    },
  },
  {
    id: "task-3",
    domainId: "dom-learning",
    title: "NodeJS Architecture Review",
    columnId: "IN_PROGRESS",
    isCompleted: false,
    xpReward: 200,
    estimatedMinutes: 30,
    sortOrder: 3,
    repeatConfig: {
      frequency: "weekdays",
      time: "18:00",
      engine: "DAILY_ROUTINE",
    },
  },
  {
    id: "task-4",
    domainId: "dom-work",
    title: "Code Review",
    columnId: "IN_PROGRESS",
    isCompleted: false,
    xpReward: 120,
    estimatedMinutes: 45,
    sortOrder: 4,
    repeatConfig: {
      frequency: "weekdays",
      time: "10:00",
      engine: "DAILY_ROUTINE",
    },
  },
  {
    id: "task-5",
    domainId: "dom-work",
    title: "Update onboarding email sequence drafts",
    columnId: "IN_PROGRESS",
    isCompleted: false,
    xpReward: 40,
    estimatedMinutes: 20,
    sortOrder: 5,
  },
  {
    id: "task-6",
    domainId: "dom-work",
    title: "Configure Vercel deployment pipeline",
    columnId: "DONE",
    isCompleted: true,
    doneAt: "2026-09-07T14:15:00Z",
    xpReward: 100,
    estimatedMinutes: 60,
    sortOrder: 6,
  },
  {
    id: "task-7",
    domainId: "dom-health",
    title: "Daily 10000 steps",
    columnId: "DONE",
    isCompleted: true,
    doneAt: "2026-09-07T17:38:00Z",
    xpReward: 25,
    estimatedMinutes: null,
    sortOrder: 7,
    repeatConfig: {
      frequency: "daily",
      engine: "DAILY_ROUTINE",
    },
  },
  {
    id: "task-8",
    domainId: "dom-health",
    title: "Doctor appointment",
    columnId: "TODO",
    isCompleted: false,
    xpReward: 50,
    estimatedMinutes: 60,
    sortOrder: 8,
    repeatConfig: {
      frequency: "specific_date",
      specificDate: "2026-09-12",
      engine: "SPECIFIC_DATE",
    },
  },
  {
    id: "task-9",
    domainId: "dom-volunteering",
    title: "CYS Volunteering Session",
    columnId: "TODO",
    isCompleted: false,
    xpReward: 200,
    estimatedMinutes: 120,
    sortOrder: 9,
    repeatConfig: {
      frequency: "custom",
      days: ["Sat"],
      engine: "CUSTOM_SCHEDULE",
    },
  },
  {
    id: "task-10",
    domainId: "dom-learning",
    title: "GitHub Course — Module Study",
    columnId: "TODO",
    isCompleted: false,
    xpReward: 100,
    estimatedMinutes: 60,
    sortOrder: 10,
    repeatConfig: {
      frequency: "custom",
      days: ["Mon", "Wed", "Fri"],
      engine: "MULTI_TASK",
      startDate: "2026-09-08",
      endDate: "2026-09-30",
    },
  },
  {
    id: "task-cys-1",
    domainId: "dom-volunteering",
    boardId: "pet-v1",
    title: "Youth Mentorship Workshop Planning",
    columnId: "TODO",
    isCompleted: false,
    xpReward: 30,
    estimatedMinutes: 45,
    sortOrder: 11,
  },
  {
    id: "task-cys-2",
    domainId: "dom-volunteering",
    boardId: "pet-v1",
    title: "Volunteer Registration & Logistics",
    columnId: "IN_PROGRESS",
    isCompleted: false,
    xpReward: 50,
    estimatedMinutes: 60,
    sortOrder: 12,
  },
  {
    id: "task-cys-3",
    domainId: "dom-volunteering",
    boardId: "pet-v1",
    title: "Community Outreach & Sponsor Deck",
    columnId: "IN_PROGRESS",
    isCompleted: false,
    xpReward: 40,
    estimatedMinutes: 30,
    sortOrder: 13,
  },
];
